[package]

name = "mod_hello"
version = "0.0.2"

[lib]
name = "mod_hello"
crate-type = ["dylib"]

[dependencies]
interpolate_idents = "*"

[dependencies.apache2]
path = "../.."
features = ["apache22"]
